### ISSUE TITLE
Please include installation instructions for non-MELPA users

### ISSUE THREAD

**Issue by bish0polis** [purcell/emacs-hcl-mode#3]
(from syohex/emacs-hcl-mode#14) 
Some people cannot use MELPA.

Can we please have a simple installation comment included, so that we can ensure we're not missing a step? I know -- it's easy to install, with a copy here and there. Please include that so we know we've done the simple by-hand step required, for our assurance.

Thanks!

**Comment by purcell** [comment]
Thanks. I feel like people who are deliberately not using `package.el` these days are either:

* Already familiar with copying elisp files and adding them to their load path, or
* Using an alternative, like `elget` or `straight`.

But I've briefly noted the process in the README now.
