### ISSUE TITLE
Create hashicorp-emacs org

### ISSUE THREAD

**Issue by Fuco1** [purcell/emacs-hcl-mode#9]
Recently I "took over" co-maintainership of terraform-mode (https://github.com/emacsorphanage/terraform-mode) and I was thinking it might be useful to make a common organization for hashicorp related modes, such as hcl-mode, terraform-mode and my (yet unreleased) nomad-mode.

It would make it a little bit more visible to the users and google/search engines as well as hashicorp itself.  Currently there's a lot of forks flying around and it's not very clear what versions are the "official" ones.

WDYT, does it make sense?  If yes, we could then also transfer terraform-mode out of the orphanage as it will again receive regular updates. (cc @tarsius)

Edit: I would also like to become co-maintainer on this package.  I use hashicorp products daily and so I have incentive to add features to these modes. WDYT @purcell?

**Comment by tarsius** [comment]
Makes sense to me.

**Comment by purcell** [comment]
Yeah, no problem for me. Happy to transfer this repo to a new org we're both in.

**Comment by fkupchik** [comment]
did it happen already?
I'd love to see these modes updated under the new org.

**Comment by purcell** [comment]
> did it happen already?
> I'd love to see these modes updated under the new org.

Not yet. I just sent @Fuco1 an invitation to be a collaborator here, but if he'd like to create a new org then I'd support that, as I wrote above. However, I wonder if it's best not to call it "hashicorp-emacs" — that sounds a somewhat like it's operated by that company.

**Comment by Fuco1** [comment]
Actually the Hashicorp team is quite active on Github, it might be reasonable to also move the repos under their namespace. There is a bunch of open source projects which are community supported living there.

@tgross I don't know if you are the right person, but we've discussed a bunch of issues over in the Nomad repo so you come to mind when thinking about Hashicorp staff.  Do you think there might be some interest for this move, or can you direct some more appropriate person over to me/this thread?

**Comment by tgross** [comment]
Hi folks! As it happens, I'm an hcl-mode user myself so I'd be happy to help champion that sort of thing internally. 

As you've probably noticed @Fuco1 there's a bit of a soft split in behavior where in Terraform HCL is being used as a "language for configuration language", and in Nomad (which I work on) and Consul/Vault it's more of a "configuration language with nice interpolation features." So I know there's been a lot of work happening on LSP support for Terraform, too, but I'm not particularly close to the work of the "editor experience" folks who have doing that. 

Let me find the right folks to chat with and I'll report back when I know more!

**Comment by tgross** [comment]
Hi folks! I had a chat with the folks who would be the internal owners of this sort of project and we're going to decline on bringing this and other HCL modes into the HashiCorp organization. Effectively we don't have the resources available to dedicate to parallel approaches to editor support, and they don't want to "promote" an alternative to the work that team is focused on around [`terraform-ls`](https://github.com/hashicorp/terraform-ls).

Speaking personally, it'd probably wouldn't burn _too_ much political capital for me and the small contingent of other Emacs ~fanatics~ enthusiasts at HashiCorp to try to pull these projects into the HashiCorp GitHub org anyways. But to be totally honest, without resources dedicated from HashiCorp, this probably isn't a great deal for community maintainers. The repos would end up subject to compliance and security initiatives that y'all wouldn't be looped in on until after everything was decided. And there'd be internal pressure around the GPL license, adding telemetry(!), etc. That being said, those of us who want a lighter-weight alternative to the LSP have been nudged to contribute here wherever we can lend our expertise.

Also, I checked in with our legal folks about the proposed org name because that tripped my spidey senses, and they would steer away from calling it "hashicorp"-anything because of confusion around whether it's "official". `emacs-hcl` or `hcl-emacs` was proposed as an alternative.

**Comment by purcell** [comment]
Cool, I created an hcl-emacs org, invited both of you guys to it, and I've transferred this repo there.

**Comment by purcell** [comment]
I also just took the liberty of transferring terraform-mode to the same org, hope that's okay @Fuco1. I should be able to set perms for you guys if/when you accept the org invitations.

**Comment by purcell** [comment]
MELPA recipes updated accordingly.

**Comment by Fuco1** [comment]
> I also just took the liberty of transferring terraform-mode to the same org, hope that's okay @Fuco1. I should be able to set perms for you guys if/when you accept the org invitations.

Definitely great!  Thanks Steve :)

@tgross It's not really a LSP alternative though.  At least in Emacs it's common to have a LANGUAGE-mode (usually providing syntax colors) and on top of that LSP enabled features, like navigation or refactorings.  If/once terraform-ls ships syntax highlighting for LSP, both lsp-mode and elgot Emacs LSP clients should support that out of the box.  But I get all the reasons mentioned, and it wouldn't really change much for me anyway, being the co-maintainer of terraform-mode.  Thanks for looking into it, it's really nice that you folks interact with the community so much.

@purcell I'll go ahead and close this issue with the org being created and the modes transferred. If there's anything left to do, feel free to reopen/comment.

**Comment by radeksimko** [comment]
👋🏻 I'm one of the folks working on the Editor Experience team @tgross mentioned.

Just to clarify the context here about the LSP and Terraform/HCL overlap. I think there's relatively little overlap, both currently and in the future. We do maintain [TextMate grammars](https://github.com/hashicorp/syntax/tree/main/syntaxes) for HCL and Terraform (they are intentionally separate) and _HCL_ VS Code extension https://github.com/hashicorp/vscode-hcl which is - again - intentionally separate from the Terraform extension. I do not expect the _Terraform_ LS to provide any "plain HCL" functionality.

_HCL_ does not imply any keywords (schema), e.g. a piece of config such as `resource "foo" "bar" {}` should be treated the same as `nonsense "blah" {}`. This is also why I'd expect there will not be any strong need for an _HCL_ language server, completion etc.

The only two possible relevant features would be formatting and _maybe_ semantic highlighting, but the latter is debatable, as given the context above it wouldn't really be "semantic" but rather "syntactic". Even with formatting, it's important to note that formatting rules do differ between HCL-based languages (i.e. `terraform fmt` rules will differ from `nomad fmt` etc.)

Whether or not LSP is involved I do expect that most editors will need to have some HCL integration, just like the one you all maintain, which provides exactly the basic functionality such as "static" syntax highlighting. As already mentioned, we do not unfortunately have enough people/time to maintain the emacs one, or any other than VS Code one at the moment, so thank you for all your efforts in maintaining it. ❤️ 

Semi-related, there is this Terraform mode which integrates with our LS https://emacs-lsp.github.io/lsp-mode/page/lsp-terraform-ls/

**Comment by purcell** [comment]
Thanks for the extra context and pointers, @radeksimko. Keep up the good work!
